import type { Metadata } from "next";
import "./globals.css";

//components
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-[#F2E5BF] antialiased">
        <Header />
        {children}
      </body>
    </html>
  );
}
